version: "3.9"

# Local development infrastructure for CloudShop
services:
  postgres:
    image: postgres:16-alpine
    container_name: cloudshop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-cloudshop}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cloudshop}
      POSTGRES_DB: ${POSTGRES_DB:-cloudshop}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudshop

  redis:
    image: redis:7-alpine
    container_name: cloudshop-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudshop

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: cloudshop-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTIC_PORT:-9200}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 >/dev/null"]
      interval: 15s
      timeout: 10s
      retries: 10
    networks:
      - cloudshop

  payment-mock:
    image: wiremock/wiremock:3.9.1
    container_name: cloudshop-payment-mock
    restart: unless-stopped
    command: ["--verbose", "--port", "8080"]
    ports:
      - "${PAYMENT_MOCK_PORT:-8080}:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:8080/__admin/health | grep -q '""status"":' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudshop

networks:
  cloudshop:
    name: cloudshop

volumes:
  pgdata:
  esdata:

